config/routes.rb
Rails.application.routes.draw do

  get 'user/home' => 'user#home'
  get 'user/login' => 'user#login'
  post 'user/login' => 'user#check'
  get 'user/logout' => 'user#logout'
  post 'user/logout' => 'user#logout'
  resources :registration


  get '/', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'


  resources :gossips

  resources :gossips do
    resources :comments
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord


end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes 
  has_many :anonymous_commentors
end

app/models/user.rb
class User < ApplicationRecord
	has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  	@comment = Comment.new
  end

  def create
  	@gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.create(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @comment = @gossip.comments.find(params[:id])
    @comment.destroy
    redirect_to gossips_path(@gossip)
  end
 
  private
  def comment_params
  	params.require(:comment).permit(:anonymous_commentor, :body)
  end




end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
  	@gossips = Gossip.all
  end
  
  def new
  	@gossip = Gossip.new
  end

  def show
  	@gossip = Gossip.find(params[:id])
  end

  def create
  	@gossip = Gossip.create(parameters)

  	p @gossip
  	redirect_to gossips_path(@gossip.id)
  end

  def edit
  	@gossip = Gossip.find(params[:id])
	@gossip.save
  end

  def update
  	@gossip = Gossip.find(params[:id])
  	@gossip.update(parameters)
  	redirect_to gossip_path(@gossip.id)
  end 

  def destroy
  	@gossip = Gossip.find(params[:id])
  	@gossip.delete
  	redirect_to gossips_path
  end

  private
  def parameters
  	params.require(:gossip).permit(:anonymous_gossiper, :content)
  end

end

app/controllers/registration_controller.rb
 class RegistrationController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(name: params["user"]["name"], email: params["user"]["email"], password: params["user"]["password"]).save
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def home

  end

  def login

  end

  def logout
    session[:user_id] = nil
    flash[:info] = "Tu as été déconnecté"
  end

  def check
    @current_user = User.where(name: params["/users/login"][:name], password: params["/users/login"][:password]).first
    if @current_user
      session[:user_id] = @current_user.id
      flash[:info] = "Tu es connecté en tant que #{@current_user.name} !"
      redirect_to "/gossip/index"
    else
      session[:user_id] = nil
      flash[:info] = "Échec de la connexion"
      redirect_to "/user/login"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gossips/create.html.erb
<h2> Félicitations <%= @gossip.anonymous_gossiper %>, j'espère que tu es content, tu es une petite balance vu que tu viens de créer un gossip ! </h2>

<br> <br>

<h3> Voilà ton gossip : </h3> <br> <br> 

<h5> <%= @gossip.content %> </h5>   <br>

<% @gossips.each do |key| %>

<a href="<%= gossips_show_path(key.id) %>" class="btn btn-primary"> Modifier ce gossip </a>

<% end %>

app/views/gossips/edit.html.erb
<div class="center jumbotron">


<h1>Éditer mon gossip</h1>

<p>
Tape ici ton nouveau Gossip, petite balance :


  <%= form_for @gossip do |f| %>
<div class="form-group" >
   <%= label_tag 'Pseudo :' %>
   <%= f.text_field :anonymous_gossiper, class: "form-control" %> <br> <br> 
</div>

<div class="form-group" >
    <%= label_tag 'Contenu :' %>
    <%= f.text_area :content, class: "form-control" %> <br> <br>
</div>

<div class="form-group" >
    <%= f.submit "Modifier mon gossip", class: "btn btn-primary" %>
</div>

  <% end %>

</p>
 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 


</div>

app/views/gossips/index.html.erb
<div class="center jumbotron">


 <h2> Voici la liste de tous les gossips à ce jour : </h2> <br>
<p>

<% @gossips.each do |key| %>
<h6>
<i> ''<%= key.content %>'' </i> <br>
Auteur: <b> <%= key.anonymous_gossiper %>      <%= link_to "Lâcher un commentaire / Modifier le gossip", gossip_path(key.id), method: :get %> </b>

</h6>

<br><br>

<% end %> </p>

</div>

app/views/gossips/new.html.erb
<div class="center jumbotron">

<p>

  <%= form_for @gossip do |f| %>
<div class="form-group" >
   <%= label_tag 'Pseudo :' %>
   <%= f.text_field :anonymous_gossiper, class: "form-control" %> <br> <br> 
</div>

<div class="form-group" >
    <%= label_tag 'Contenu :' %>
    <%= f.text_area :content, class: "form-control" %> <br> <br>
</div>

<div class="form-group" >
    <%= f.submit "Créer mon gossip", class: "btn btn-primary" %>
</div>

  <% end %>

</p>

 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 
 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 
<p> Pourquoi tu scrolles jusqu'en bas petit malin ? </p>

</div>

app/views/gossips/show.html.erb
<div class="center jumbotron">

<h1> Page du gossip </h1> <br>

<h5> <i>'' <%= @gossip.content %> ''</i> </h5>
<div class= "form-group" >

<%= link_to 'Éditer', edit_gossip_path(@gossip.id) %> |
<%= link_to 'Retour', gossips_path %>

<a href= "<%= gossip_path(@gossip.id) %>"" class='btn btn-danger' data-confirm="Êtes-vous sûr de vouloir supprimer ce gossip ? Cette action est irréversible." data-method="delete"> Supprimer </a>
<br><br>



 <h2>Commentaires: </h2>
<% @gossip.comments.each do |key| %>
  <p>

    <strong>Commentaire:</strong>
    <%= key.body %> <br>

    <i> Pseudo: </i>
    <strong><%= key.anonymous_commentor %> </strong> <br>

  <%= link_to 'Supprimer le commentaire', gossip_comment_path(:gossip_id),
               method: :delete,
               data: { confirm: 'Es-tu sûr de vouloir supprimer ce commentaire ?' } %>
</p>


<% end %>



</p>
 
<h2>Ajouter un commentaire:</h2>
<%= form_with(model: [ @gossip, @gossip.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :anonymous_commentor %><br>
    <%= form.text_field :anonymous_commentor %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

</div>
 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 


</div>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/layouts/_header.html.erb
  <link rel="icon" href="http://chittagongit.com//images/google-g-icon/google-g-icon-0.jpg">


<header class="navbar navbar-expand-lg navbar-dark" style="background-color: #3b5998;">

  <a class="navbar-brand" href="#"> <strong> 🍆The G Project 🍆 </strong> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
      <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Chercher un potin/utilisateur">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"> 🔍 </button>
    </form>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil <span class="sr-only">(current)</span></a>
      </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/gossips/new" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Nouveau gossip
        </a>

      </li>
        <li class="nav-item">
        <a class="nav-link" href="/gossips">Gossips</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="/contact">Contact</a>
              <li class="nav-item active">
        <a class="nav-link" href="/registration/new">Créer un compte<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/user/login">Se connecter</a>
      </li>
      </li>


    </ul>

  </div>
</nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>

<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />


    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-CfCAYEgrdtRrpvjGKxoaRy5ge1ggMbxNSpEkY+XqdfdRTUkRrYZVB2z99E7BsEDZ" crossorigin="anonymous">

    <%= render "layouts/header.html.erb" %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="center jumbotron">

<h2> <i> Réalisé en pair-programming par : </i> </h2> <br> <br> <br>

<h4>	<li> Paul Rivière (Paul Rivière) </li>
	<li> Patrick Razafindrakoto (patpasha) </li> </h4>

 <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 

<h8> Avec bon 💝 </h8>

</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h4> <b> Avec The Gossip Project, partagez et restez en contact avec votre entourage. </b></h4> <br><br><br>
 
  <h2>Inscription </h2>
   
   <h5> C'est gratuit (et ça le restera toujours) </h5> <br>
  <%= link_to "Inscription", '/registration/new', class: "btn btn-lg btn-success" %>



  
   <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 

</div>

app/views/user/login.html.erb
<div class="center jumbotron">


<br>
<h1>Connexion</h1>
<br>
<%= form_for '/users/login' do |f| %>
  <%= f.text_field :name, class: "form-control form-control-lg", placeholder: "Pseudo" %>
  <br>
  <%= f.password_field :password, class: "form-control form-control-lg", placeholder: "Mot de passe" %>
  <br>
  <br>
  <%= f.submit "Se connecter", class: "btn btn-primary btn-lg" %>
<% end %>


<br><br><br><br><br><br>
<br><br><br>
<br><br><br><br><br><br><br><br>

</div>